mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from books.views import about_pages

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'mysite.views.first_page'),
    url(r'^west/', include('west.urls')),
    url(r'^time/$', 'mysite.views.current_datetime'),
    url(r'^time/plus/(\d{1,2})/$', 'mysite.views.hours_ahead'),
    url(r'^display/$', 'mysite.views.display_meta'),
    #url(r'^search-form/$', 'books.views.search_form'),
    url(r'^search/$', 'books.views.search'),
    url(r'^contact/$', 'contact.views.contact'),
    url(r'^contact/thanks/$', 'contact.views.thanks'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html')),
    url(r'^about/(\w+)/$', about_pages),
)

west/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^$', 'west.views.first_page'),
	url(r'^staff/', 'west.views.staff'),
	url(r'^templay/', 'west.views.templay'),
)

books/models.py
#coding=utf-8

from django.db import models

# Create your models here.

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province =  models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __unicode__(self):
        return self.name

class Meta:
    ordering = ['-name']

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, verbose_name='e-mail')

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class BookManager(models.Manager):
    def title_count(self, keyword):
        return self.filter(title__icontains=keyword).count()

class DahlBookManager(models.Manager):
    def get_query_set(self):
        return super(DahlBookManager, self).get_query_set().filter(authors='1')

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)
    num_pages = models.IntegerField(blank=True, null=True)
    object = BookManager()
    dahl_objects = DahlBookManager()

    def __unicode__(self):
        return self.title

contact/models.py
from django.db import models

# Create your models here.

west/models.py
from django.db import models

class Character(models.Model):
	name = models.CharField(max_length=200)
	def __unicode__(self):
		return self.name

contact/forms.py
__author__ = 'liangnaihua'

from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your E-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from books.models import Book
from django.http import Http404
from django.template import TemplateDoesNotExist
from django.views.generic.simple import direct_to_template

# Create your views here.

def search_form(request):
	return render(request,'books/search_form.html')

def search(request):
#if 'q' in request.GET and request.GET['q']:
#	q = request.GET['q']
#	books = Book.objects.filter(title__icontains=q)
#	return render(request,'books/search_results.html', {'books':books, 'query':q})
#else:
#	#return HttpResponse('Please submit a search term.')
#	return render(request,'books/search_form.html', {'error':True})
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
        elif len(q) > 20:
            errors.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render(request, 'books/search_results.html', {'books':books, 'query':q})
    return render(request, 'books/search_form.html', {'errors':errors})

def about_pages(request, page):
    try:
        return direct_to_template(request, template="about/%s,html" % page)
    except TemplateDoesNotExist:
        raise Http404()

contact/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.http import HttpResponse
from contact.forms import ContactForm

# from django.shortcuts import render_to_response
# from django.shortcuts import RequestContext

# Create your views here.

# def contact(request):
#     errors=[]
#     if request.method == 'POST':
#         if not request.POST.get('subject', ''):
#             errors.append('Enter a subject.')
#         if not request.POST.get('message', ''):
#             errors.append('Enter a message.')
#         if request.POST.get('email') and '@' not in request.POST['email']:
#             errors.append('Enter a valid e-mail address.')
#         if not errors:
#             send_mail(request.POST['subject'],
#                       request.POST['message'],
#                       request.POST.get('email', 'noreply@example.com'),
#                       ['siteowner@example.com'],
#                       )
#             return HttpResponseRedirect('/contact/thanks/')
#     return render(request, 'contact/contact_form.html', {
#         'errors': errors,
#         'subject': request.POST.get('subject', ''),
#         'message': request.POST.get('message', ''),
#         'email': request.POST.get('email', ''),
#     })

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreplay@emample.com'),
                ['liangnaihua@sungymobile.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
            initial={'subject': 'I love your site!'}
        )
    return render(request, 'contact/contact_form.html', {'form':form})

def thanks(request):
	return HttpResponse("Thanks!")

mysite/views.py
#coding=utf-8

from django.http import HttpResponse, Http404
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render

import datetime

def first_page(request):
	#return HttpResponse("<p>Welcome to the page at %s</p>" % request.get_host())
	ua = request.META.get('HTTP_USER_AGENT', 'unknown')
	return HttpResponse("Your browser is %s" %ua)

def current_datetime(request):
	current_date = datetime.datetime.now()
#	t = get_template('current_datetime.html')
#	html = t.render(Context({'current_datetime':now}))
	current_section = "hello"
	return render(request, 'mysite/current_datetime.html', locals())
#	return HttpResponse(html)



# def current_datetime(request):
# 	now = datetime.datetime.now()
# 	html = "<html><body>It is now %s.</body></html>" % now
# 	return HttpResponse(html)

def hours_ahead(request, offset):
	try:
		offset = int(offset)	
	except ValueError:
		raise Http404()
	dt = datetime.datetime.now() + datetime.timedelta(hours=offset)
	html = "<html><body>In %s hour(s), it will be %s.</body></html>" % (offset, dt)
	return HttpResponse(html)

def display_meta(request):
	values = request.META.items()
	values.sort()
	html = []
	for k, v in values:
		html.append('<tr><td>%s,%s</td></tr>' % (k, str(v)))
	return HttpResponse('<table>%s</table>' % '\n'.join(html))

west/views.py
#coding=utf-8
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from west.models import Character

def first_page(request):
	return HttpResponse("<p>此次</p>")

def staff(request):
	#staff_list = Character.objects.all()
	#staff_str = map(str, staff_list)
	#return HttpResponse("<p>"+' '.join(staff_str) + "</p>")
	staff_list = Character.objects.all()
	#staff_str = map(str, staff_list)
	#context = {'label':' '.join(staff_str)}
	#return render(request, 'templay.html', context)
	return render(request, 'templay.html',{'staffs':staff_list})

def templay(request):
	context	= {}
	context['label'] = 'Hello World!'
	return render(request, 'templay.html', context)

mysite/templates/current_datetime.html
<html>
<body>
{% include "mysite/nav.html" %}
It is now {{ current_datetime }}.
</body></html>

mysite/templates/letter.html
<html>
<head><title>Ordering notice</title></head>

<body>

<h1>Ordering notice</h1>

<p>Dear {{ person_name }},</p>

<p>Thanks for placing an order from {{ company }}. It's scheduled to
ship on {{ ship_date|date:"F j, Y" }}.</p>

<p>Here are the items you've ordered:</p>

<ul>
{% for item in item_list %}
	<li>{{ item }}</li>
{% endfor %}
</ul>

{% if ordered_warranty %}
	<p>Your warranty information will be included in the packaging.</p>
{% else %}
	<p>You didn't order a warranty, so you're on your own when
	the products inevitably stop working.</p>
{% endif %}

<p>Sincerely,<br />{{ company }}</p>

</body>
</html>

mysite/templates/mysite/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<h1>My helpful timestamp site</h1>
	{% block content %}{% endblock %}
	{% block footer %}
	<hr>
	<p>Thanks for visiting my site.</p>
	{% endblock %}
</body>
</html>

mysite/templates/mysite/current_datetime.html
{% extends "mysite/base.html" %}

{% block title %}The Current time{% endblock %}

{% block content %}
<p>It is now {{ current_date }}.</p>
{% endblock %}

mysite/templates/mysite/nav.html
<div id="nav">
	You are in: {{ current_section }}
</div>

templates/books/search_form.html
<html>

<head>
	<title>Search</title>
</head>

<body>
	{% if errors %}
		<ul>
			{% for error in errors%}
				<li> {{error}}</li>
			{% endfor %}
		</ul>
	{% endif%}
	<form action="" method="get">
		<input type="text" name="q">
		<input type="submit" value="Search">
	</form>
</body>

</html>

templates/books/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
	<p><Found {{ books|length }} book{{ books|pluralize }}.</p>
	<ul>
		{% for book in books %}
		<li> {{ book.title }} </li>
		{% endfor %}
	</ul>
{% else %}
	<p>No books matched your search criteria.</p>
{% endif %}

templates/contact/contact_form.html
{#<html>#}
{#<head>#}
{#	<title>Contact us</title>#}
{#</head>#}
{##}
{#<body>#}
{#	<h1>Contact us</h1>#}
{#	{% if errors %}#}
{#		<ul>#}
{#			{% for error in errors %}#}
{#				<li> {{ error }} </li>#}
{#			{% endfor %}#}
{#		</ul>#}
{#	{% endif %}#}
{##}
{#	<form action="/contact/" method="post">#}
{#        {% csrf_token %}#}
{#		<p>Subject: <input type="text" name="subject" value="{{ subject }}"></p>#}
{#		<p>Your e-mail (optionnal): <input type="text" name="email" value="{{ email }}"></p>#}
{#		<p>Message: <textarea name="message" rows="10" cols="50"> {{ message }} </textarea></p>#}
{#		<input type="submit" value="Submit">#}
{#	</form>#}
{#</body>#}
{##}
{#</html>#}

<html>
<head>
    <title>Contact us</title>
    <style type="text/css">
        ul.errorlist {
            margin: 0;
            padding: 0;
        }
        .errorlist li {
            background-color: red;
            color: white;
            display: block;
            font-size: 10px;
            margin: 0 0 3px;
            padding: 4px 5px;
        }
    </style>
</head>

<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">{% csrf_token %}
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your Email address:</label>
            {{ form.email }}
        </div>
{#        <div class="field">#}
{#            {{ form.message.errors }}#}
{#            <label for="id_message">Message:</label>#}
{#            {{ form.message }}#}
{#        </div>#}
        <div class="field{% if form.message.errors %} errors {% endif %}">
            {% if form.message.errors %}
                <ul>
                    {% for error in form.message.errors %}
                        <li><strong>{{ error }}</strong></li>
                    {% endfor %}
                </ul>
            {% endif %}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <input type="submit" value="Submit">
    </form>
    </body>
</html>

west/templates/templay.html
{% for item in staffs %}
<p>{{ item.id }}, {{item}}</p>
{% endfor %}